apiVersion: apps/v1
kind : Deployment
metadata: 
  name: mongo-db
spec: 
 minReadySeconds: 180
 replicas: 1 
 selector:
   matchLabels:
     env: qa
 template:
    metadata:
      labels: 
        env: qa
    spec: 
      containers:
        - name: mongos
          image: mongo:5.0
          ports: 
            - containerPort: 27017
          env:
            - name: USER_NAME
              valueFrom: 
                secretKeyRef:
                  name: mongosecr 
                  key: mongo-user
            - name: USER_PWD
              valueFrom: 
                secretKeyRef:
                  name: mongosecr 
                  key:  mongo-password
      
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    env: qa 
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017


              