---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  minReadySeconds: 180
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
          - containerPort: 3000
        env:
          - name: USER_NAME
            valueFrom: 
              secretKeyRef:
                name: mongosecr 
                key: mongo-user
          - name: USER_PWD
            valueFrom: 
              secretKeyRef:
                name: mongosecr 
                key: mongo-password  
          - name: DB-URL 
            valueFrom:
              configMapKeyRef:
                 name: mongo-config    
                 key: mongo-url
      
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      